// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNQryENtJ4VwqlzOKoeTtGFjGlGUArKhE',
    appId: '1:535424118627:web:9409a7787e942443c46d56',
    messagingSenderId: '535424118627',
    projectId: 'expense-management-app-1d3e1',
    authDomain: 'expense-management-app-1d3e1.firebaseapp.com',
    storageBucket: 'expense-management-app-1d3e1.firebasestorage.app',
    measurementId: 'G-PTTMK187X5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNtl4U6P4K-EgEYwo2ehCg3-cDrEgotjY',
    appId: '1:535424118627:android:02aefecbe030efa7c46d56',
    messagingSenderId: '535424118627',
    projectId: 'expense-management-app-1d3e1',
    storageBucket: 'expense-management-app-1d3e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9Mcr85ZBBKXNtPV2c0NF9v0pfLbCjzy8',
    appId: '1:535424118627:ios:ccf50dba286bfdfec46d56',
    messagingSenderId: '535424118627',
    projectId: 'expense-management-app-1d3e1',
    storageBucket: 'expense-management-app-1d3e1.firebasestorage.app',
    iosBundleId: 'com.example.expensesManager',
  );
}
